// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  id,
  username,
  refresh_token,
  client_ip,
  user_agent,
  is_blocked,
  expire_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, username, refresh_token, client_ip, user_agent, is_blocked, expire_at, created_at
`

type CreateSessionParams struct {
	ID           pgtype.UUID
	Username     string
	RefreshToken string
	ClientIp     string
	UserAgent    string
	IsBlocked    bool
	ExpireAt     pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.Username,
		arg.RefreshToken,
		arg.ClientIp,
		arg.UserAgent,
		arg.IsBlocked,
		arg.ExpireAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.ClientIp,
		&i.UserAgent,
		&i.IsBlocked,
		&i.ExpireAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, username, refresh_token, client_ip, user_agent, is_blocked, expire_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.RefreshToken,
		&i.ClientIp,
		&i.UserAgent,
		&i.IsBlocked,
		&i.ExpireAt,
		&i.CreatedAt,
	)
	return i, err
}
